"""
Group-based Cellular Neighborhood Analysis and Visualization

This script reads the original source h5ad tiles plus lightweight CN-label JSONs written by cn_unified_kmeans.py and generates:
1. Unified analysis visualizations (unified_analysis folder):
   - Unified CN composition heatmap
   - Overall and per-tile neighborhood frequency graphs
2. Group-specific analysis (<tile_size>mm_groups folder):
   - Group-based CN composition comparisons (vs overall)
   - Group-specific frequency visualizations
   - Combined per-tile frequency figure, grouped by category

Note: Individual per-tile spatial CN maps are generated by the separate
print_cn_tiles.py script, since that step re-renders one figure per
tile (potentially hundreds) and is the slowest part of the pipeline — keeping
it separate lets you skip it on faster iteration cycles.

All processed h5ad tiles are loaded into memory once per run and reused across
every downstream step (unified analysis, each group's subset, and the combined
per-tile frequency figure), rather than re-reading tiles from disk repeatedly.
"""

import numpy as np
import pandas as pd
import anndata as ad
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.patheffects as path_effects
import seaborn as sns
import json
import argparse
from pathlib import Path
from typing import List, Dict, Optional, Tuple, Set
import warnings
warnings.filterwarnings('ignore')

# Heatmap cell annotations were 12pt; bumped to 16pt. Related axis/title sizes +4 for consistency.
HEATMAP_ANNOT_FONT = 16
HEATMAP_AXIS_LABEL_FONT = 16
HEATMAP_TICK_LABEL_FONT = 16
HEATMAP_TITLE_FONT = 18

# Full cell-type names (h5ad / data_preparation.py) -> short labels for figure axes only.
CELL_TYPE_TO_ABBREV = {
    "Others": "Oth",
    "Tumor": "Tum",
    "Lymphocyte": "Lym",
    "Fibroblast/Stroma": "Fib/Str",
}

# Left-to-right column order on composition heatmaps (full names as in adata / CSV).
CELL_TYPE_HEATMAP_ORDER_FULL: Tuple[str, ...] = (
    "Others",
    "Tumor",
    "Lymphocyte",
    "Fibroblast/Stroma",
)


def _canonical_cell_type_column_order(columns) -> List[str]:
    """Stable order: canonical list first, then any other columns in their original order."""
    col_list = list(columns)
    seen: set = set()
    unique_cols: List[str] = []
    for c in col_list:
        s = str(c)
        if s not in seen:
            seen.add(s)
            unique_cols.append(s)
    canon_set = set(CELL_TYPE_HEATMAP_ORDER_FULL)
    ordered = [c for c in CELL_TYPE_HEATMAP_ORDER_FULL if c in seen]
    remaining = [c for c in unique_cols if c not in canon_set]
    return ordered + remaining


def _reorder_cell_type_columns_canonical(df: pd.DataFrame) -> pd.DataFrame:
    """Reorder columns for heatmaps; indices unchanged."""
    order = _canonical_cell_type_column_order(df.columns)
    return df.loc[:, order].copy()


def _rename_cell_type_columns_for_plot(df: pd.DataFrame) -> pd.DataFrame:
    """Copy of df with column names abbreviated for heatmaps only (CSVs unchanged)."""
    out = df.copy()
    out.columns = [CELL_TYPE_TO_ABBREV.get(str(c), str(c)) for c in out.columns]
    return out


def _prepare_composition_df_for_heatmap(df: pd.DataFrame) -> pd.DataFrame:
    """Canonical cell-type order, then abbreviations, for composition heatmaps only."""
    return _rename_cell_type_columns_for_plot(_reorder_cell_type_columns_canonical(df))


def _resolve_n_clusters_from_adata(
    adata: ad.AnnData,
    cn_key: str,
    n_clusters: Optional[int] = None,
) -> int:
    """Return the number of CNs present in data (authoritative for plot titles).

    If an explicit n_clusters is passed and disagrees with the data, warn and
    use the data count so titles match the figure.
    """
    n_from_data = int(adata.obs[cn_key].nunique())
    if n_clusters is not None and int(n_clusters) != n_from_data:
        print(
            f"  Warning: n_clusters={n_clusters} was requested, but data has "
            f"{n_from_data} unique CN labels in '{cn_key}'; "
            f"using {n_from_data} for titles."
        )
    return n_from_data


def load_tile_selection(csv_path) -> Set[str]:
    """
    Load a set of tile names to include, from a CSV with a 'tile' column
    (e.g. one row per tile: 'JN_TS_001_tile_12883_7423'). Tile names should
    match each h5ad file's stem (filename without the .h5ad extension).

    Used to restrict analysis to a subset of tiles — e.g. excluding tiles for
    QC reasons, or spot-checking a subset — without needing to move/delete
    the underlying h5ad or CN-label files.
    """
    df = pd.read_csv(csv_path)
    if 'tile' not in df.columns:
        raise ValueError(
            f"Expected a 'tile' column in {csv_path}, found columns: {list(df.columns)}"
        )
    tiles = set(df['tile'].astype(str).str.strip())
    print(f"✓ Loaded tile selection: {len(tiles)} tiles from {csv_path}")
    return tiles


def _infer_n_clusters_from_path(path: Path) -> Optional[int]:
    """Infer n_clusters from path segments like all_n_cluster=4 or results_n=4."""
    import re
    for part in [path.name, path.parent.name, *path.parts[::-1]]:
        match = re.search(r'n_clusters?[=_]?(\d+)', part)
        if match:
            return int(match.group(1))
        match = re.search(r'(?:^|[_-])n[=_](\d+)', part)
        if match:
            return int(match.group(1))
    return None


def _is_integer_cn_labels(labels) -> bool:
    """Check if CN labels are integers (1, 2, 3) vs strings (CN1, CN3-1)."""
    for x in labels:
        try:
            int(float(str(x).strip()))
        except (ValueError, TypeError):
            return False
    return True


def _sort_cn_labels_and_colors(labels, color_palette: str = 'tab20'):
    """
    Sort CN labels and return (sorted_labels, colors).
    Supports both integer labels (1, 2, 3) and string labels (CN1, CN2, CN3-1).
    """
    labels = list(labels)
    if not labels:
        return [], []

    if _is_integer_cn_labels(labels):
        int_labels = [int(float(str(x).strip())) for x in labels]
        sorted_labels = sorted(set(int_labels), key=lambda x: x)
        palette = sns.color_palette(color_palette, max(sorted_labels))
        colors = [palette[x - 1] for x in sorted_labels]
        return sorted_labels, colors
    else:
        def sort_key(s):
            s = str(s).strip()
            if not s.startswith('CN'):
                return (999, 0)
            rest = s[2:]
            if '-' in rest:
                parts = rest.split('-', 1)
                return (int(parts[0]) if parts[0].isdigit() else 999,
                        int(parts[1]) if parts[1].isdigit() else 0)
            return (int(rest) if rest.isdigit() else 999, 0)

        sorted_labels = sorted(set(labels), key=sort_key)
        n = len(sorted_labels)
        palette = sns.color_palette(color_palette, max(n, 20))[:n]
        colors = list(palette)
        return sorted_labels, colors


class GroupCNAnalyzer:
    """Analyzes cellular neighborhoods by predefined groups."""

    def __init__(
        self,
        source_h5ad_dir: str,
        cn_labels_dir: str,
        categories_json: str,
        output_dir: str,
        tile_selection: Optional[Set[str]] = None,
    ):
        """
        Initialize group CN analyzer.

        Parameters:
        -----------
        source_h5ad_dir : str
            Directory containing the ORIGINAL h5ad tiles produced by
            data_preparation.py (already have cell_type + spatial; not
            modified by clustering). Named "{tile_name}.h5ad".
        cn_labels_dir : str
            Directory containing the lightweight per-tile CN-label JSON files
            written by cn_unified_kmeans_local.py's save_cn_labels() (its
            output_dir/cn_labels/ folder). Named "{tile_name}_cn_labels.json".
        categories_json : str
            Path to JSON file mapping group name -> list of tile IDs
            (plus an optional 'metadata' key with e.g. tile_size_mm2)
        output_dir : str
            Base output directory for all results
        tile_selection : set of str, optional
            If given, restrict analysis to only these tile names (see
            load_tile_selection). Tiles not in this set are excluded even if
            present in both source_h5ad_dir and cn_labels_dir.
        """
        self.source_h5ad_dir = Path(source_h5ad_dir)
        self.cn_labels_dir = Path(cn_labels_dir)
        self.categories_json = Path(categories_json)
        self.tile_selection = tile_selection
        base_output_dir = Path(output_dir)

        with open(self.categories_json, 'r') as f:
            self.categories = json.load(f)

        self.base_output_dir = base_output_dir
        self.base_output_dir.mkdir(parents=True, exist_ok=True)
        (self.base_output_dir / 'unified_analysis').mkdir(exist_ok=True)

        # Extract tile size from metadata and create subfolder for group analysis
        tile_size_mm = self.categories.get('metadata', {}).get('tile_size_mm2', 2.0)
        tile_size_folder = f"{int(tile_size_mm)}mm_groups"
        self.output_dir = base_output_dir / tile_size_folder
        self.output_dir.mkdir(parents=True, exist_ok=True)

        # Cache of the combined, all-tiles AnnData (populated by load_all_processed_tiles,
        # reused across unified analysis, each group's subset, and the combined
        # per-tile frequency figure — avoids re-reading/re-merging tiles repeatedly)
        self._combined_adata_cache: Optional[ad.AnnData] = None

        print(f"✓ Loaded tile categories from: {self.categories_json}")
        print(f"  Groups: {list(self.categories.keys() - {'metadata'})}")
        print(f"  Source h5ad directory: {self.source_h5ad_dir}")
        print(f"  CN labels directory: {self.cn_labels_dir}")
        if self.tile_selection is not None:
            print(f"  Tile selection: {len(self.tile_selection)} tiles")
        print(f"  Base output directory: {self.base_output_dir}")
        print(f"  Group analysis output: {self.output_dir}")

    def load_all_processed_tiles(
        self,
        cn_key: str = 'cn_celltype',
        celltype_key: str = 'cell_type',
        use_cache: bool = True
    ) -> ad.AnnData:
        """
        Load each tile's original source h5ad (cell_type + spatial, untouched
        by clustering) and merge in its CN labels from the matching lightweight
        JSON file, combining all tiles into a single AnnData object. Nothing
        new is written to disk here — the merge happens in memory.

        Cells with no matching CN label (e.g. a tile that wasn't part of the
        clustering run, or an individual cell dropped somewhere upstream) are
        excluded from the combined dataset, with a warning.

        Cached after the first call (use_cache=True) so repeated calls within
        the same run don't redo this merge for every tile again.
        """
        if use_cache and self._combined_adata_cache is not None:
            return self._combined_adata_cache

        print(f"\nLoading source h5ad tiles from: {self.source_h5ad_dir}")
        print(f"Merging in CN labels from: {self.cn_labels_dir}")

        h5ad_files = sorted(self.source_h5ad_dir.glob('*.h5ad'))
        if not h5ad_files:
            raise ValueError(f"No h5ad files found in {self.source_h5ad_dir}")
        print(f"Found {len(h5ad_files)} source h5ad files")

        if self.tile_selection is not None:
            found_stems = {f.stem for f in h5ad_files}
            missing = self.tile_selection - found_stems
            if missing:
                sample = sorted(missing)[:5]
                print(f"  Warning: {len(missing)} tile(s) from the selection list were not "
                      f"found in {self.source_h5ad_dir}: {sample}"
                      f"{' ...' if len(missing) > 5 else ''}")
            h5ad_files = [f for f in h5ad_files if f.stem in self.tile_selection]
            print(f"  Tile selection applied: keeping {len(h5ad_files)} tiles")
            if not h5ad_files:
                raise ValueError("No tiles remain after applying tile_selection")

        # Map tile_name -> cn_labels json path
        cn_label_files = sorted(self.cn_labels_dir.glob('*_cn_labels.json'))
        cn_label_map = {}
        suffix = '_cn_labels'
        for f in cn_label_files:
            stem = f.stem
            if stem.endswith(suffix):
                tile_name = stem[:-len(suffix)]
                cn_label_map[tile_name] = f
        if not cn_label_map:
            raise ValueError(f"No *_cn_labels.json files found in {self.cn_labels_dir}")
        print(f"Found {len(cn_label_map)} CN-label JSON files")

        adata_list = []
        cell_type_categories = None
        n_tiles_no_labels = 0

        for i, h5ad_file in enumerate(h5ad_files, 1):
            tile_name = h5ad_file.stem
            print(f"  [{i}/{len(h5ad_files)}] Loading {tile_name}...")

            if tile_name not in cn_label_map:
                print(f"    Warning: no CN-label JSON found for {tile_name}, skipping "
                      f"(this tile wasn't part of the clustering run, or naming doesn't match)")
                n_tiles_no_labels += 1
                continue

            try:
                adata = ad.read_h5ad(h5ad_file)

                if celltype_key not in adata.obs.columns:
                    print(f"    Warning: {celltype_key} not found, skipping")
                    continue

                if 'tile_name' not in adata.obs.columns:
                    adata.obs['tile_name'] = tile_name

                # Merge in CN labels from the lightweight JSON, matching by the
                # original nucleus ID (obs_name with the "{tile_name}_" prefix
                # stripped off — this is exactly how save_cn_labels() built the keys).
                with open(cn_label_map[tile_name], 'r') as f:
                    payload = json.load(f)
                labels = payload.get('labels', {})

                prefix = f"{tile_name}_"
                cn_values = []
                matched_mask = []
                for obs_name in adata.obs_names:
                    nucleus_id = str(obs_name)[len(prefix):] if str(obs_name).startswith(prefix) else str(obs_name)
                    if nucleus_id in labels:
                        cn_values.append(labels[nucleus_id])
                        matched_mask.append(True)
                    else:
                        cn_values.append(None)
                        matched_mask.append(False)

                matched_mask = np.array(matched_mask)
                n_unmatched = (~matched_mask).sum()
                if n_unmatched:
                    print(f"    Warning: {n_unmatched}/{adata.n_obs} cells in {tile_name} had "
                          f"no matching CN label; excluding them from analysis")

                if not matched_mask.any():
                    print(f"    Warning: no cells in {tile_name} matched a CN label, skipping tile")
                    continue

                adata = adata[matched_mask].copy()
                adata.obs[cn_key] = pd.Categorical(
                    [cn_values[j] for j in range(len(cn_values)) if matched_mask[j]]
                )

                if isinstance(adata.obs[celltype_key].dtype, pd.CategoricalDtype):
                    if cell_type_categories is None:
                        cell_type_categories = adata.obs[celltype_key].cat.categories.tolist()
                        print(f"    ✓ Preserving cell type order from first tile: {cell_type_categories}")
                    else:
                        # NOTE: deliberately NOT passing ordered=True here. If this tile's
                        # categorical ends up with a different 'ordered' flag than the first
                        # tile's, ad.concat treats the dtypes as incompatible and silently
                        # falls back to plain object dtype for the whole column across all
                        # tiles — silently breaking every downstream "preserve category
                        # order" step (composition columns then default to alphabetical).
                        adata.obs[celltype_key] = adata.obs[celltype_key].astype('category')
                        adata.obs[celltype_key] = adata.obs[celltype_key].cat.set_categories(
                            cell_type_categories
                        )
                elif cell_type_categories is None:
                    adata.obs[celltype_key] = pd.Categorical(adata.obs[celltype_key])
                    cell_type_categories = adata.obs[celltype_key].cat.categories.tolist()
                    print(f"    ✓ Cell types converted to categorical, order: {cell_type_categories}")

                adata_list.append(adata)
                print(f"    ✓ Loaded {adata.n_obs} cells (with matched CN labels)")

            except Exception as e:
                print(f"    ✗ Error loading {h5ad_file}: {str(e)}")
                continue

        if n_tiles_no_labels:
            print(f"\n  Note: {n_tiles_no_labels} source tile(s) had no matching CN-label file "
                  f"and were skipped entirely.")

        if not adata_list:
            raise ValueError("No valid tiles could be loaded and matched with CN labels")

        print(f"\nCombining {len(adata_list)} tiles...")
        combined_adata = ad.concat(adata_list, join='outer')

        if cell_type_categories is not None:
            if isinstance(combined_adata.obs[celltype_key].dtype, pd.CategoricalDtype):
                combined_adata.obs[celltype_key] = combined_adata.obs[celltype_key].cat.set_categories(
                    cell_type_categories
                )
            else:
                # ad.concat fell back to object dtype (e.g. because per-tile categoricals
                # weren't perfectly aligned) — explicitly restore categorical + order here
                # rather than silently losing it for every downstream step.
                combined_adata.obs[celltype_key] = pd.Categorical(
                    combined_adata.obs[celltype_key], categories=cell_type_categories
                )
                print(f"    ✓ Restored categorical dtype/order on combined data "
                      f"(concat had reverted it to {combined_adata.obs[celltype_key].dtype})")

        print(f"✓ Combined dataset: {combined_adata.n_obs:,} cells")
        print(f"  Tiles: {combined_adata.obs['tile_name'].nunique()}")
        print(f"  Cell types: {combined_adata.obs[celltype_key].nunique()}")

        if use_cache:
            self._combined_adata_cache = combined_adata

        return combined_adata

    def get_group_subset(self, combined_adata: ad.AnnData, group_name: str) -> ad.AnnData:
        """
        Subset the already-loaded combined AnnData to just the tiles belonging
        to group_name, instead of re-reading each tile's h5ad file from disk.
        """
        if group_name not in self.categories:
            raise ValueError(f"Group '{group_name}' not found in categories")

        tile_names = set(self.categories[group_name])
        mask = combined_adata.obs['tile_name'].isin(tile_names)
        subset = combined_adata[mask].copy()

        found_tiles = subset.obs['tile_name'].unique().tolist()
        missing = tile_names - set(found_tiles)
        if missing:
            print(f"  Warning: {len(missing)} tiles for group '{group_name}' not found "
                  f"in loaded data: {sorted(missing)[:5]}{'...' if len(missing) > 5 else ''}")

        if subset.n_obs == 0:
            raise ValueError(f"No cells found for group: {group_name}")

        print(f"✓ Group '{group_name}': {len(found_tiles)} tiles, {subset.n_obs:,} cells")
        return subset

    def compute_cn_composition(
        self,
        adata: ad.AnnData,
        cn_key: str = 'cn_celltype',
        celltype_key: str = 'cell_type'
    ) -> Tuple[pd.DataFrame, pd.DataFrame]:
        """Compute cell phenotype fractions in each CN for the given adata
        (works for the full combined dataset or any group subset)."""
        composition = pd.crosstab(
            adata.obs[cn_key],
            adata.obs[celltype_key],
            normalize='index'
        )

        if isinstance(adata.obs[celltype_key].dtype, pd.CategoricalDtype):
            cell_type_order = adata.obs[celltype_key].cat.categories.tolist()
            existing_cols = [col for col in cell_type_order if col in composition.columns]
            remaining_cols = [col for col in composition.columns if col not in existing_cols]
            composition = composition[existing_cols + remaining_cols]

        composition_zscore = composition.apply(lambda x: (x - x.mean()) / x.std(), axis=0)
        return composition, composition_zscore

    def calculate_neighborhood_frequency(
        self,
        adata: ad.AnnData,
        cn_key: str = 'cn_celltype',
        group_by_tile: bool = False
    ) -> pd.DataFrame:
        """
        Calculate the frequency of each cellular neighborhood for the given adata
        (works for the full combined dataset or any group subset).
        """
        print(f"\nCalculating neighborhood frequency...")

        if group_by_tile:
            frequency_df = pd.crosstab(
                adata.obs['tile_name'],
                adata.obs[cn_key],
                normalize='index'
            )
            print(f"  ✓ Calculated CN frequency per tile")
        else:
            cn_counts = adata.obs[cn_key].value_counts().sort_index()
            total_cells = len(adata.obs)
            cn_percentages = (cn_counts / total_cells * 100).round(2)

            frequency_df = pd.DataFrame({
                'Count': cn_counts,
                'Percentage': cn_percentages
            })
            frequency_df.index.name = 'Cellular_Neighborhood'
            frequency_df = frequency_df.reset_index()
            print(f"  ✓ Calculated overall CN frequency")
            print(f"    Total cells: {total_cells:,}")

        return frequency_df

    def visualize_unified_cn_composition(
        self,
        adata: ad.AnnData,
        composition_zscore: pd.DataFrame,
        k: int,
        n_clusters: int,
        figsize: Tuple[int, int] = (12, 8),
        cmap: str = 'coolwarm',
        vmin: float = -2,
        vmax: float = 2,
        save_path: Optional[str] = None,
        show_values: bool = True
    ):
        """Visualize unified CN composition as heatmap across ALL tiles.

        Column order follows CELL_TYPE_HEATMAP_ORDER_FULL (then abbreviations), not
        adata categorical order (which is often alphabetical after multi-tile concat).
        """
        print("\nVisualizing unified CN composition heatmap...")

        fig, ax = plt.subplots(figsize=figsize)

        z_plot = _prepare_composition_df_for_heatmap(composition_zscore)
        sns.heatmap(
            z_plot,
            cmap=cmap,
            center=0,
            vmin=vmin,
            vmax=vmax,
            cbar_kws={'label': 'Z-score'},
            linewidths=0.5,
            linecolor='white',
            ax=ax,
            annot=show_values,
            fmt='.2f' if show_values else '',
            annot_kws={'size': HEATMAP_ANNOT_FONT}
        )

        ax.set_xlabel('Cell Type', fontsize=HEATMAP_AXIS_LABEL_FONT, fontweight='bold')
        ax.set_ylabel('Cellular Neighborhood', fontsize=HEATMAP_AXIS_LABEL_FONT, fontweight='bold')

        n_tiles = adata.obs['tile_name'].nunique()
        n_cells = adata.n_obs
        title = (f'Unified Cell Type Composition by Cellular Neighborhood\n'
                f'(k={k}, n_clusters={n_clusters}, {n_tiles} tiles, {n_cells:,} cells)\n'
                f'Z-score scaled by column')
        ax.set_title(title, fontsize=HEATMAP_TITLE_FONT, fontweight='bold', pad=20)

        plt.setp(ax.get_xticklabels(), rotation=45, ha='right', fontsize=HEATMAP_TICK_LABEL_FONT)
        plt.setp(ax.get_yticklabels(), rotation=0, fontsize=HEATMAP_TICK_LABEL_FONT)

        plt.tight_layout()

        if save_path:
            plt.savefig(save_path, dpi=300, bbox_inches='tight')
            print(f"  ✓ Saved unified heatmap to: {save_path}")

        plt.close(fig)
        return fig

    def visualize_unified_neighborhood_frequency(
        self,
        adata: ad.AnnData,
        cn_key: str = 'cn_celltype',
        group_by_tile: bool = False,
        figsize: Tuple[int, int] = (12, 6),
        save_path: Optional[str] = None,
        color_palette: str = 'tab20',
        show_tile_names: bool = False
    ):
        """Generate a graph showing neighborhood frequency (overall, or stacked per tile)."""
        print(f"\nGenerating neighborhood frequency graph...")

        frequency_df = self.calculate_neighborhood_frequency(adata, cn_key, group_by_tile)

        n_cns = len(adata.obs[cn_key].cat.categories)
        if n_cns <= 20:
            colors_palette = sns.color_palette(color_palette, n_cns)
        else:
            colors_palette = sns.color_palette('husl', n_cns)

        if group_by_tile:
            fig, ax = plt.subplots(figsize=figsize)

            sorted_labels, colors_sorted = _sort_cn_labels_and_colors(frequency_df.columns, color_palette)
            sorted_cols = [c for c in sorted_labels if c in frequency_df.columns]
            frequency_df_sorted = frequency_df[sorted_cols]

            frequency_df_sorted.plot(kind='bar', stacked=True, ax=ax,
                                     color=colors_sorted, width=0.8)

            ax.set_xlabel('Tile', fontsize=12, fontweight='bold')
            ax.set_ylabel('Frequency (Proportion)', fontsize=12, fontweight='bold')
            ax.set_title('Cellular Neighborhood Frequency by Tile',
                        fontsize=14, fontweight='bold', pad=15)
            ax.legend(title='Cellular Neighborhood', bbox_to_anchor=(1.05, 1),
                     loc='upper left', fontsize=9)
            if show_tile_names:
                ax.set_xticklabels(ax.get_xticklabels(), rotation=45, ha='right')
            else:
                ax.set_xticklabels([])
            ax.grid(axis='y', alpha=0.3, linestyle='--')

            plt.tight_layout()
        else:
            plt.close('all')
            fig, ax = plt.subplots(1, 1, figsize=figsize)

            cn_labels_col = frequency_df['Cellular_Neighborhood']
            sorted_labels, colors_list = _sort_cn_labels_and_colors(cn_labels_col, color_palette)
            order = {lab: i for i, lab in enumerate(sorted_labels)}
            frequency_df_sorted = frequency_df.copy()
            frequency_df_sorted['_ord'] = frequency_df_sorted['Cellular_Neighborhood'].map(order)
            frequency_df_sorted = frequency_df_sorted.sort_values('_ord').drop(columns=['_ord'])
            colors_for_bars = [colors_list[order[lab]] for lab in frequency_df_sorted['Cellular_Neighborhood']]

            bars = ax.bar(frequency_df_sorted['Cellular_Neighborhood'].astype(str),
                         frequency_df_sorted['Count'],
                         color=colors_for_bars)

            ax.set_xlabel('Cellular Neighborhood', fontsize=12, fontweight='bold')
            ax.set_ylabel('Cell Count', fontsize=12, fontweight='bold')
            ax.set_title('CN Frequency (Count)',
                        fontsize=14, fontweight='bold', pad=15)
            ax.grid(axis='y', alpha=0.3, linestyle='--')

            text_outline = [path_effects.withStroke(linewidth=3, foreground='white')]
            for bar, count, pct in zip(bars,
                                      frequency_df_sorted['Count'],
                                      frequency_df_sorted['Percentage']):
                height = bar.get_height()
                ax.text(bar.get_x() + bar.get_width()/2., height,
                       f'{int(count):,}',
                       ha='center', va='bottom', fontsize=14, fontweight='bold',
                       color='black', path_effects=text_outline)
                ax.text(bar.get_x() + bar.get_width()/2., height/2,
                       f'{pct:.1f}%',
                       ha='center', va='center', fontsize=14,
                       color='black', fontweight='bold', path_effects=text_outline)

            plt.setp(ax.get_xticklabels(), rotation=45, ha='right')

            plt.tight_layout()

        if save_path:
            plt.savefig(save_path, dpi=300, bbox_inches='tight')
            print(f"  ✓ Saved frequency graph to: {save_path}")

        if not group_by_tile:
            csv_path = self.base_output_dir / 'unified_analysis' / 'neighborhood_frequency.csv'
            frequency_df.to_csv(csv_path, index=False)
            print(f"  ✓ Saved frequency data to: {csv_path}")

        plt.close(fig)
        return fig

    def visualize_cn_composition_heatmap(
        self,
        composition_zscore: pd.DataFrame,
        group_name: str,
        n_cells: int,
        overall_zscore: Optional[pd.DataFrame] = None,
        figsize=(12, 8),
        save_path: Optional[str] = None
    ):
        """Visualize CN composition heatmap for a group, showing difference from overall."""
        fig, ax = plt.subplots(figsize=figsize)

        if overall_zscore is not None:
            common_rows = composition_zscore.index.intersection(overall_zscore.index)
            common_cols = composition_zscore.columns.intersection(overall_zscore.columns)
            final_cols = _canonical_cell_type_column_order(list(common_cols))

            group_aligned = composition_zscore.loc[common_rows, final_cols]
            overall_aligned = overall_zscore.loc[common_rows, final_cols]

            zscore_diff = overall_aligned - group_aligned
            zscore_diff = zscore_diff.reindex(columns=final_cols)

            annot_array = np.empty((len(group_aligned.index), len(final_cols)), dtype=object)
            for i, row_idx in enumerate(group_aligned.index):
                for j, col_idx in enumerate(final_cols):
                    diff_val = zscore_diff.loc[row_idx, col_idx]
                    group_val = group_aligned.loc[row_idx, col_idx]
                    annot_array[i, j] = f'{diff_val:.2f}({group_val:.2f})'

            zscore_diff_plot = _prepare_composition_df_for_heatmap(zscore_diff)
            sns.heatmap(
                zscore_diff_plot,
                cmap='RdYlGn_r',
                center=0,
                vmin=-3,
                vmax=3,
                cbar_kws={'label': 'Z-score Difference (Overall - Group)'},
                linewidths=0.5,
                linecolor='white',
                ax=ax,
                annot=annot_array,
                fmt='',
                annot_kws={'size': HEATMAP_ANNOT_FONT}
            )

            title = (f'Cell Fraction Difference from Overall\n'
                    f'Group: {group_name} ({n_cells:,} cells)\n'
                    f'Format: Difference(Group Z-score)')
        else:
            composition_plot = _prepare_composition_df_for_heatmap(composition_zscore)

            sns.heatmap(
                composition_plot,
                cmap='RdYlGn_r',
                center=0,
                vmin=-2,
                vmax=2,
                cbar_kws={'label': 'Z-score'},
                linewidths=0.5,
                linecolor='white',
                ax=ax,
                annot=True,
                fmt='.2f',
                annot_kws={'size': HEATMAP_ANNOT_FONT}
            )

            title = (f'Cell Type Composition by Cellular Neighborhood\n'
                    f'Group: {group_name} ({n_cells:,} cells)\n'
                    f'Z-score scaled by column')

        ax.set_xlabel('Cell Type', fontsize=HEATMAP_AXIS_LABEL_FONT, fontweight='bold')
        ax.set_ylabel('Cellular Neighborhood', fontsize=HEATMAP_AXIS_LABEL_FONT, fontweight='bold')
        ax.set_title(title, fontsize=HEATMAP_TITLE_FONT, fontweight='bold', pad=20)

        plt.setp(ax.get_xticklabels(), rotation=45, ha='right', fontsize=HEATMAP_TICK_LABEL_FONT)
        plt.setp(ax.get_yticklabels(), rotation=0, fontsize=HEATMAP_TICK_LABEL_FONT)
        plt.tight_layout()

        if save_path:
            plt.savefig(save_path, dpi=300, bbox_inches='tight')
            print(f"  ✓ Saved heatmap to: {save_path}")

        plt.close(fig)

    def visualize_group_neighborhood_frequency(
        self,
        frequency_df: pd.DataFrame,
        group_name: str,
        figsize=(10, 6),
        save_path: Optional[str] = None,
        color_palette: str = 'tab20'
    ):
        """Visualize neighborhood frequency for a single group."""
        plt.close('all')
        fig, ax = plt.subplots(1, 1, figsize=figsize)

        cn_labels_col = frequency_df['Cellular_Neighborhood']
        sorted_labels, colors_list = _sort_cn_labels_and_colors(cn_labels_col, color_palette)
        order = {lab: i for i, lab in enumerate(sorted_labels)}
        frequency_df_sorted = frequency_df.copy()
        frequency_df_sorted['_ord'] = frequency_df_sorted['Cellular_Neighborhood'].map(order)
        frequency_df_sorted = frequency_df_sorted.sort_values('_ord').drop(columns=['_ord'])
        colors_for_bars = [colors_list[order[lab]] for lab in frequency_df_sorted['Cellular_Neighborhood']]

        bars = ax.bar(
            frequency_df_sorted['Cellular_Neighborhood'].astype(str),
            frequency_df_sorted['Count'],
            color=colors_for_bars
        )

        ax.set_xlabel('Cellular Neighborhood', fontsize=12, fontweight='bold')
        ax.set_ylabel('Cell Count', fontsize=12, fontweight='bold')
        ax.set_title(f'CN Frequency (Count) - {group_name}',
                    fontsize=14, fontweight='bold', pad=15)
        ax.grid(axis='y', alpha=0.3, linestyle='--')

        text_outline = [path_effects.withStroke(linewidth=3, foreground='white')]

        for bar, count, pct in zip(bars,
                                   frequency_df_sorted['Count'],
                                   frequency_df_sorted['Percentage']):
            height = bar.get_height()
            ax.text(bar.get_x() + bar.get_width()/2., height,
                   f'{int(count):,}',
                   ha='center', va='bottom', fontsize=14, fontweight='bold',
                   color='black', path_effects=text_outline)
            ax.text(bar.get_x() + bar.get_width()/2., height/2,
                   f'{pct:.1f}%',
                   ha='center', va='center', fontsize=14,
                   color='black', fontweight='bold', path_effects=text_outline)

        plt.setp(ax.get_xticklabels(), rotation=45, ha='right')
        plt.tight_layout()

        if save_path:
            plt.savefig(save_path, dpi=300, bbox_inches='tight')
            print(f"  ✓ Saved frequency graph to: {save_path}")

        plt.close(fig)

    def visualize_all_groups_per_tile_frequency(
        self,
        combined_adata: ad.AnnData,
        cn_key: str = 'cn_celltype',
        figsize=(16, 8),
        save_path: Optional[str] = None,
        color_palette: str = 'tab20'
    ):
        """
        Visualize per-tile frequency for all groups in one figure, bars clustered
        by group. Computed directly from the already-loaded combined_adata
        instead of re-reading every tile's h5ad file from disk again.
        """
        print(f"\nGenerating combined per-tile frequency for all groups...")

        groups = [key for key in self.categories.keys() if key != 'metadata']
        tile_to_group = {tile: group for group in groups for tile in self.categories[group]}

        # Frequency per tile, computed in one crosstab over the whole combined dataset
        frequency_df = pd.crosstab(
            combined_adata.obs['tile_name'],
            combined_adata.obs[cn_key],
            normalize='index'
        )
        frequency_df.columns = [str(col) for col in frequency_df.columns]

        # Keep only tiles that belong to a known group
        frequency_df = frequency_df[frequency_df.index.isin(tile_to_group.keys())]

        sorted_labels, colors = _sort_cn_labels_and_colors(frequency_df.columns, color_palette)
        sorted_cols = [str(c) for c in sorted_labels if str(c) in frequency_df.columns]
        frequency_df = frequency_df[sorted_cols]

        group_order = {group: idx for idx, group in enumerate(groups)}
        sorted_tiles = sorted(frequency_df.index,
                            key=lambda t: (group_order.get(tile_to_group.get(t, ''), 999), t))
        frequency_df = frequency_df.reindex(sorted_tiles)

        fig, ax = plt.subplots(figsize=figsize)
        frequency_df.plot(kind='bar', stacked=True, ax=ax, color=colors, width=0.8, legend=False)

        from matplotlib.patches import Rectangle
        legend_handles = [
            Rectangle((0, 0), 1, 1, facecolor=color, edgecolor='black', linewidth=0.5, alpha=1.0)
            for color in colors
        ]
        legend_labels = [str(lab) if str(lab).startswith('CN') else f'CN {lab}' for lab in sorted_labels]

        group_boundaries = {}
        current_idx = 0
        for group_name in groups:
            group_tiles = [t for t in sorted_tiles if tile_to_group.get(t) == group_name]
            if group_tiles:
                n_tiles = len(group_tiles)
                group_boundaries[group_name] = (current_idx, current_idx + n_tiles - 1)
                current_idx += n_tiles

        x_positions = [(start + end) / 2.0 for start, end in group_boundaries.values()]
        ax.set_xticks(x_positions)
        ax.set_xticklabels(list(group_boundaries.keys()), rotation=45, ha='right',
                          fontsize=11, fontweight='bold')

        for start, end in list(group_boundaries.values())[:-1]:
            ax.axvline(x=end + 0.5, color='black', linestyle='--', linewidth=2.5)

        ax.set_xlabel('Group', fontsize=12, fontweight='bold')
        ax.set_ylabel('Frequency (Proportion)', fontsize=12, fontweight='bold')
        ax.set_title('Cellular Neighborhood Frequency by Tile (Grouped by Category)',
                    fontsize=14, fontweight='bold', pad=15)
        ax.legend(handles=legend_handles, labels=legend_labels,
                 title='Cellular Neighborhood', bbox_to_anchor=(1.05, 1),
                 loc='upper left', fontsize=9)
        ax.grid(axis='y', alpha=0.3, linestyle='--')

        plt.tight_layout()
        if save_path:
            plt.savefig(save_path, dpi=300, bbox_inches='tight')
            print(f"  ✓ Saved combined per-tile frequency to: {save_path}")
        plt.close(fig)

    def generate_unified_analysis(
        self,
        combined_adata: ad.AnnData,
        k: int = 20,
        n_clusters: Optional[int] = None,
        cn_key: str = 'cn_celltype',
        celltype_key: str = 'cell_type',
        color_palette: str = 'tab20'
    ) -> pd.DataFrame:
        """
        Generate unified analysis visualizations from the already-loaded
        combined_adata. Returns composition_zscore so callers (e.g. per-group
        analysis) can reuse it without recomputing or re-reading from disk.
        """
        print(f"\n{'='*80}")
        print("GENERATING UNIFIED ANALYSIS VISUALIZATIONS")
        print(f"{'='*80}")

        n_clusters = _resolve_n_clusters_from_adata(combined_adata, cn_key, n_clusters)

        composition, composition_zscore = self.compute_cn_composition(
            combined_adata, cn_key, celltype_key
        )

        comp_path = self.base_output_dir / 'unified_analysis' / 'unified_cn_composition.csv'
        composition.to_csv(comp_path)
        print(f"  ✓ Saved composition to: {comp_path}")

        heatmap_path = self.base_output_dir / 'unified_analysis' / 'unified_cn_composition_heatmap.png'
        self.visualize_unified_cn_composition(
            combined_adata,
            composition_zscore,
            k=k,
            n_clusters=n_clusters,
            save_path=str(heatmap_path),
            show_values=True
        )

        overall_freq_path = self.base_output_dir / 'unified_analysis' / 'neighborhood_frequency_overall.png'
        self.visualize_unified_neighborhood_frequency(
            combined_adata,
            cn_key=cn_key,
            group_by_tile=False,
            figsize=(10, 6),
            save_path=str(overall_freq_path),
            color_palette=color_palette
        )

        per_tile_freq_path = self.base_output_dir / 'unified_analysis' / 'neighborhood_frequency_per_tile.png'
        self.visualize_unified_neighborhood_frequency(
            combined_adata,
            cn_key=cn_key,
            group_by_tile=True,
            figsize=(14, 8),
            save_path=str(per_tile_freq_path),
            color_palette=color_palette
        )

        print("\nSaving summary statistics...")
        tile_names = sorted(combined_adata.obs['tile_name'].unique().tolist())

        summary = {
            'analysis_type': 'Unified Cellular Neighborhoods',
            'n_tiles': len(tile_names),
            'tile_names': tile_names,
            'total_cells': int(combined_adata.n_obs),
            'total_genes': int(combined_adata.n_vars),
            'parameters': {
                'k_neighbors': k,
                'n_clusters': n_clusters,
                'celltype_key': celltype_key
            },
            'cn_distribution': combined_adata.obs[cn_key].value_counts().to_dict(),
            'cell_type_distribution': combined_adata.obs[celltype_key].value_counts().to_dict(),
            'cn_composition': composition.to_dict()
        }

        def convert_to_native(obj):
            converters = {
                np.integer: int,
                np.floating: float,
                np.ndarray: lambda x: x.tolist()
            }
            for dtype, converter in converters.items():
                if isinstance(obj, dtype):
                    return converter(obj)
            if isinstance(obj, dict):
                return {k: convert_to_native(v) for k, v in obj.items()}
            if isinstance(obj, list):
                return [convert_to_native(item) for item in obj]
            return obj

        summary = convert_to_native(summary)

        summary_path = self.base_output_dir / 'unified_analysis' / 'unified_cn_summary.json'
        with open(summary_path, 'w') as f:
            json.dump(summary, f, indent=2)
        print(f"  ✓ Saved summary to: {summary_path}")

        print(f"\n✓ Unified analysis complete!")
        print(f"  Results saved to: {self.base_output_dir}/unified_analysis/")

        return composition_zscore

    def analyze_group(
        self,
        combined_adata: ad.AnnData,
        group_name: str,
        cn_key: str = 'cn_celltype',
        celltype_key: str = 'cell_type',
        color_palette: str = 'tab20',
        overall_zscore: Optional[pd.DataFrame] = None
    ):
        """Run complete analysis for a single group, subsetting the already-loaded
        combined_adata rather than re-reading that group's tiles from disk."""
        print(f"\n{'='*80}")
        print(f"ANALYZING GROUP: {group_name.upper()}")
        print(f"{'='*80}")

        adata = self.get_group_subset(combined_adata, group_name)

        if overall_zscore is None:
            print("\nLoading overall CN composition for comparison...")
            overall_comp_path = self.base_output_dir / 'unified_analysis' / 'unified_cn_composition.csv'
            if overall_comp_path.exists():
                overall_composition = pd.read_csv(overall_comp_path, index_col=0)
                overall_zscore = overall_composition.apply(lambda x: (x - x.mean()) / x.std(), axis=0)
            else:
                print(f"  Warning: Overall composition file not found at {overall_comp_path}; "
                      f"group heatmap will show raw z-scores instead of a difference-from-overall.")

        print("\nComputing CN composition...")
        composition, composition_zscore = self.compute_cn_composition(
            adata, cn_key, celltype_key
        )

        csv_path = self.output_dir / f'cn_cell_fraction_{group_name}.csv'
        composition.to_csv(csv_path)
        print(f"  ✓ Saved composition CSV to: {csv_path}")

        print("\nGenerating cell fraction difference heatmap...")
        heatmap_path = self.output_dir / f'cell_fraction_difference_{group_name}.png'
        self.visualize_cn_composition_heatmap(
            composition_zscore,
            group_name,
            adata.n_obs,
            overall_zscore=overall_zscore,
            save_path=str(heatmap_path)
        )

        print("\nCalculating neighborhood frequency...")
        frequency_df = self.calculate_neighborhood_frequency(adata, cn_key)

        print("\nGenerating neighborhood frequency graph...")
        freq_path = self.output_dir / f'neighborhood_frequency_{group_name}.png'
        self.visualize_group_neighborhood_frequency(
            frequency_df,
            group_name,
            save_path=str(freq_path),
            color_palette=color_palette
        )

        print(f"\n✓ Group analysis complete for: {group_name}")
        print(f"  Total cells: {adata.n_obs:,}")
        print(f"  Tiles: {len(self.categories[group_name])}")

    def analyze_all_groups(
        self,
        cn_key: str = 'cn_celltype',
        celltype_key: str = 'cell_type',
        color_palette: str = 'tab20',
        k: int = 20,
        n_clusters: Optional[int] = None,
        generate_unified: bool = True
    ):
        """
        Run analysis for all groups, plus (optionally) unified analysis.
        Loads all h5ad tiles exactly once and reuses that in-memory dataset
        across every step below.
        """
        banner = "=" * 80
        print(f"\n{banner}")
        print("GROUP-BASED CELLULAR NEIGHBORHOOD ANALYSIS")
        print(f"{banner}")
        print(f"Source h5ad directory: {self.source_h5ad_dir}")
        print(f"CN labels directory: {self.cn_labels_dir}")
        print(f"Categories JSON: {self.categories_json}")
        print(f"Base output directory: {self.base_output_dir}")
        print(f"Group analysis output: {self.output_dir}")
        print(f"{banner}\n")

        # Load every tile exactly once; reused for unified analysis, each
        # group's subset, and the combined per-tile frequency figure below.
        combined_adata = self.load_all_processed_tiles(cn_key, celltype_key)

        overall_zscore = None
        if generate_unified:
            overall_zscore = self.generate_unified_analysis(
                combined_adata,
                k=k,
                n_clusters=n_clusters,
                cn_key=cn_key,
                celltype_key=celltype_key,
                color_palette=color_palette
            )

        groups = [key for key in self.categories.keys() if key != 'metadata']

        for group in groups:
            self.analyze_group(
                combined_adata, group, cn_key, celltype_key, color_palette,
                overall_zscore=overall_zscore
            )

        print(f"\n{'='*80}")
        print("GENERATING COMBINED PER-TILE FREQUENCY FIGURE")
        print(f"{'='*80}")
        per_tile_path = self.output_dir / 'neighborhood_frequency_per_tile_all_groups.png'
        self.visualize_all_groups_per_tile_frequency(
            combined_adata,
            cn_key=cn_key,
            save_path=str(per_tile_path),
            color_palette=color_palette
        )

        print(f"\n{banner}")
        print("ALL ANALYSES COMPLETE!")
        print(f"{banner}")
        print(f"\nResults saved to: {self.base_output_dir}/")
        print(f"\nUnified analysis (if generated):")
        print(f"  - unified_analysis/unified_cn_composition_heatmap.png")
        print(f"  - unified_analysis/neighborhood_frequency_overall.png")
        print(f"  - unified_analysis/neighborhood_frequency_per_tile.png")
        print(f"\nGroup-specific analysis:")
        print(f"  - {self.output_dir.name}/cell_fraction_difference_{{group}}.png")
        print(f"  - {self.output_dir.name}/cn_cell_fraction_{{group}}.csv")
        print(f"  - {self.output_dir.name}/neighborhood_frequency_{{group}}.png")
        print(f"  - {self.output_dir.name}/neighborhood_frequency_per_tile_all_groups.png")
        print(f"\nNote: individual per-tile spatial CN maps are generated separately "
              f"by print_cn_tiles.py")


def main():
    """Main function."""
    parser = argparse.ArgumentParser(
        description='Group-based Cellular Neighborhood Analysis'
    )
    parser.add_argument(
        '--source_h5ad_dir',
        required=True,
        help='Directory containing the ORIGINAL h5ad tiles from data_preparation.py '
             '(named "{tile_name}.h5ad"; already has cell_type + spatial)'
    )
    parser.add_argument(
        '--cn_labels_dir',
        required=True,
        help='Directory containing the lightweight per-tile CN-label JSON files '
             '(output_dir/cn_labels/ from cn_unified_kmeans_local.py)'
    )
    parser.add_argument(
        '--categories_json',
        required=True,
        help='Path to JSON file mapping group name -> list of tile IDs '
             '(plus optional metadata.tile_size_mm2)'
    )
    parser.add_argument(
        '--output_dir',
        required=True,
        help='Base output directory for results'
    )
    parser.add_argument(
        '--cn_key',
        default='cn_celltype',
        help='Column name for CN labels (default: cn_celltype). Use cn_celltype_sub for sub-clustered results.'
    )
    parser.add_argument(
        '--celltype_key',
        default='cell_type',
        help='Column name for cell types (default: cell_type)'
    )
    parser.add_argument(
        '--color_palette',
        default='tab20',
        help='Color palette (default: tab20, supports up to 20 distinct colors)'
    )
    parser.add_argument(
        '--group',
        default=None,
        help='Analyze specific group only (default: all groups)'
    )
    parser.add_argument(
        '--k',
        type=int,
        default=20,
        help='Number of nearest neighbors used (for titles only, default: 20)'
    )
    parser.add_argument(
        '--n_clusters',
        type=int,
        default=None,
        help='Number of clusters used (for titles only). If omitted, inferred '
             'from path or from unique CN labels in the data.'
    )
    parser.add_argument(
        '--no-generate_unified',
        dest='generate_unified',
        action='store_false',
        default=True,
        help='Skip unified analysis visualizations (default: generate unified analysis)'
    )
    parser.add_argument(
        '--tile_list_csv',
        default=None,
        help="Optional CSV with a 'tile' column listing which tile names to "
             "include (e.g. 'JN_TS_001_tile_12883_7423'), one per row. Tiles "
             "not in this list are excluded, even if present in both "
             "source_h5ad_dir and cn_labels_dir. Leave unset to use all tiles."
    )

    args = parser.parse_args()

    # Auto-detect cn_key for sub-clustered data
    if '_sub' in str(args.cn_labels_dir) and args.cn_key == 'cn_celltype':
        args.cn_key = 'cn_celltype_sub'
        print(f"Note: Detected sub-clustered data (_sub in path), using cn_key='cn_celltype_sub'")

    if args.n_clusters is None:
        inferred = _infer_n_clusters_from_path(Path(args.cn_labels_dir))
        if inferred is not None:
            args.n_clusters = inferred
            print(f"Note: Inferred n_clusters={args.n_clusters} from cn_labels_dir path")

    tile_selection = load_tile_selection(args.tile_list_csv) if args.tile_list_csv else None

    analyzer = GroupCNAnalyzer(
        source_h5ad_dir=args.source_h5ad_dir,
        cn_labels_dir=args.cn_labels_dir,
        categories_json=args.categories_json,
        output_dir=args.output_dir,
        tile_selection=tile_selection,
    )

    if args.group:
        combined_adata = analyzer.load_all_processed_tiles(args.cn_key, args.celltype_key)
        analyzer.analyze_group(
            combined_adata,
            args.group,
            cn_key=args.cn_key,
            celltype_key=args.celltype_key,
            color_palette=args.color_palette
        )
    else:
        analyzer.analyze_all_groups(
            cn_key=args.cn_key,
            celltype_key=args.celltype_key,
            color_palette=args.color_palette,
            k=args.k,
            n_clusters=args.n_clusters,
            generate_unified=args.generate_unified
        )


if __name__ == '__main__':
    main()
